require('dotenv').config();const express=require('express'),cors=require('cors'),mongoose=require('mongoose'),crypto=require('crypto'),bcrypt=require('bcryptjs'),Razorpay=require('razorpay');const {MenuItem,Settings,Order,Profile}=require('./models');const {auth,permit}=require('./auth');
const app=express();app.use(cors({origin:process.env.CLIENT_URL?.split(',')||true}));app.use(express.json({limit:'1mb'}));
const razorpay=process.env.RAZORPAY_KEY_ID?new Razorpay({key_id:process.env.RAZORPAY_KEY_ID,key_secret:process.env.RAZORPAY_KEY_SECRET}):null;const paise=n=>Math.round(Number(n)||0);
async function settings(){return await Settings.findOne()||await Settings.create({});}
async function calculateQuote(body){const s=await settings(),items=body.items||[];if(!s.ordersEnabled){const error=new Error('Restaurant is closed for orders');error.status=503;throw error}const ids=items.map(x=>x.itemId);const menu=await MenuItem.find({_id:{$in:ids},available:true}).lean();if(!items.length||menu.length!==ids.length){const error=new Error('One or more items are unavailable');error.status=400;throw error}let subtotal=0,quantity=0;for(const line of items){const item=menu.find(x=>String(x._id)===line.itemId);const qty=paise(line.quantity);if(qty<1){const error=new Error('Cart quantities are invalid');error.status=400;throw error}quantity+=qty;subtotal+=item.pricePaise*qty;for(const selected of line.modifierNames||[]){const m=item.modifiers.find(x=>x.active&&x.name===selected);if(!m){const error=new Error('Invalid modifier');error.status=400;throw error}subtotal+=m.pricePaise*qty}}const distance=Math.max(0,Number(body.distanceKm)||0),included=Number(s.deliveryIncludedKm??0),delivery=distance<=included?s.deliveryBasePaise:s.deliveryBasePaise+Math.ceil((distance-included)*10)*(s.deliveryPer100mPaise??100),packaging=quantity*s.itemPackagingPaise;const tax=Math.round(subtotal*s.taxBps/10000),gateway=s.gatewayFeeEnabled?Math.round(subtotal*s.gatewayFeeBps/10000):0,platform=s.platformFeeEnabled===false?0:s.platformFeePaise;return {subtotalPaise:subtotal,taxPaise:tax,deliveryPaise:delivery,packagingPaise:packaging,platformFeePaise:platform,gatewayFeePaise:gateway,totalPaise:subtotal+tax+delivery+packaging+platform+gateway}}
app.get('/api/health',(req,res)=>res.json({ok:true,mongo:mongoose.connection.readyState===1}));
app.post('/api/auth/profile',auth,async(req,res)=>{const fullName=String(req.body.fullName||'').trim(),mobile=String(req.body.mobile||'').trim();if(fullName.length<2||!/^\+?[0-9]{10,15}$/.test(mobile))return res.status(400).json({error:'Enter your full name and a valid mobile number'});const admins=(process.env.ADMIN_EMAILS||'').split(',').map(x=>x.trim().toLowerCase());const role=admins.includes(String(req.user.email).toLowerCase())?'OWNER':'CUSTOMER';const profile=await Profile.findOneAndUpdate({supabaseId:req.user.id},{email:req.user.email,fullName,mobile,role,onboardingComplete:true},{new:true,upsert:true,setDefaultsOnInsert:true});res.json(profile)});
app.get('/api/auth/me',auth,async(req,res)=>{const profile=await Profile.findOne({supabaseId:req.user.id});res.json({...req.user,onboardingComplete:profile?.onboardingComplete||false})});
app.get('/api/menu',async(req,res)=>{const items=await MenuItem.find({}).sort({category:1,name:1}).lean();res.json(items.map(item=>({...item,description:`${item.category}${item.description?` · ${item.description}`:''}`}))) });
app.post('/api/delivery/quote',async(req,res,next)=>{try{res.json(await calculateQuote(req.body))}catch(error){next(error)}});
app.post('/api/payments/razorpay/create',auth,async(req,res,next)=>{try{if(!razorpay)return res.status(503).json({error:'Razorpay is not configured'});const order=await Order.findOne({_id:req.body.orderId,customerId:req.user.id,status:'PAYMENT_PENDING'});if(!order)return res.status(404).json({error:'Pending order not found'});if(order.payment?.razorpayOrderId)return res.json({id:order.payment.razorpayOrderId,amount:order.totalPaise,currency:'INR',keyId:process.env.RAZORPAY_KEY_ID});const payment=await razorpay.orders.create({amount:order.totalPaise,currency:'INR',receipt:`gd_${order._id}`});order.payment={provider:'razorpay',state:'PENDING',razorpayOrderId:payment.id};await order.save();res.json({id:payment.id,amount:payment.amount,currency:payment.currency,keyId:process.env.RAZORPAY_KEY_ID});}catch(error){next(error)}});
app.post('/api/payments/razorpay/verify',auth,async(req,res,next)=>{try{const {razorpay_order_id,razorpay_payment_id,razorpay_signature,orderId}=req.body;const order=await Order.findOne({_id:orderId,customerId:req.user.id});if(!order)return res.status(404).json({error:'Order not found'});if(order.payment?.razorpayOrderId!==razorpay_order_id)return res.status(400).json({error:'Payment order does not match'});const expected=crypto.createHmac('sha256',process.env.RAZORPAY_KEY_SECRET).update(`${razorpay_order_id}|${razorpay_payment_id}`).digest('hex');const received=String(razorpay_signature||'');if(!received||!crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(received)))return res.status(400).json({error:'Invalid payment signature'});if(order.payment?.state==='PAID')return res.json({verified:true});const otp=String(crypto.randomInt(100000,1000000));order.payment={provider:'razorpay',state:'PAID',razorpayOrderId:razorpay_order_id,razorpayPaymentId:razorpay_payment_id};order.status='CONFIRMED';order.deliveryOtpHash=await bcrypt.hash(otp,12);order.statusHistory.push({status:'CONFIRMED',actor:'payment',note:'Payment verified',at:new Date()});await order.save();res.json({verified:true,deliveryOtp:otp,orderId:order.id});}catch(error){next(error)}});
app.post('/api/rider/orders/:id/verify-otp',auth,permit('rider'),async(req,res)=>{const order=await Order.findById(req.params.id);if(!order||!order.deliveryOtpHash)return res.status(404).json({error:'Delivery OTP is unavailable'});if(order.riderId&&order.riderId!==req.user.id)return res.status(403).json({error:'This order is assigned to another rider'});if(!await bcrypt.compare(String(req.body.otp||''),order.deliveryOtpHash))return res.status(400).json({error:'Incorrect OTP'});if(order.status==='DELIVERED')return res.json({delivered:true});order.riderId=req.user.id;order.status='DELIVERED';order.statusHistory.push({status:'DELIVERED',actor:req.user.id,note:'Delivery OTP verified',at:new Date()});await order.save();res.json({delivered:true});});
app.patch('/api/rider/availability',auth,permit('rider'),async(req,res,next)=>{try{const profile=await Profile.findOneAndUpdate({supabaseId:req.user.id},{$set:{riderOnline:!!req.body.online}},{new:true});res.json({online:!!profile?.riderOnline})}catch(error){next(error)}});
app.post('/api/orders',auth,async(req,res,next)=>{try{const profile=await Profile.findOne({supabaseId:req.user.id});const address=req.body.customer?.address?.trim(),location=req.body.customer?.location;if(!profile?.onboardingComplete||!address)return res.status(400).json({error:'Add your profile and delivery address before ordering'});const q=await calculateQuote(req.body);const menu=await MenuItem.find({_id:{$in:req.body.items.map(x=>x.itemId)}}).lean();const items=req.body.items.map(line=>{const item=menu.find(x=>String(x._id)===line.itemId);return {itemId:item._id,name:item.name,quantity:paise(line.quantity),unitPricePaise:item.pricePaise,modifiers:[]}});const safeLocation=Number.isFinite(location?.latitude)&&Number.isFinite(location?.longitude)?{latitude:Number(location.latitude),longitude:Number(location.longitude),accuracy:Number(location.accuracy)||null,capturedAt:new Date()}:undefined;const order=await Order.create({customerId:req.user.id,customer:{name:profile.fullName,mobile:profile.mobile,address,landmark:String(req.body.customer?.landmark||''),location:safeLocation},items,subtotalPaise:q.subtotalPaise,taxPaise:q.taxPaise,deliveryPaise:q.deliveryPaise,packagingPaise:q.packagingPaise,platformFeePaise:q.platformFeePaise,gatewayFeePaise:q.gatewayFeePaise,totalPaise:q.totalPaise,status:'PAYMENT_PENDING',statusHistory:[{status:'PAYMENT_PENDING',actor:req.user.id,note:'Order created',at:new Date()}]});res.status(201).json(order)}catch(error){next(error)}});
app.get('/api/orders/mine',auth,async(req,res,next)=>{try{res.json(await Order.find({customerId:req.user.id,'payment.state':'PAID'}).sort({createdAt:-1}).lean())}catch(error){next(error)}});
app.get('/api/rider/orders',auth,permit('rider'),async(req,res,next)=>{try{res.json(await Order.find({'payment.state':'PAID',status:{$in:['CONFIRMED','OUT_FOR_DELIVERY']},riderId:req.user.id}).sort({createdAt:1}).lean())}catch(error){next(error)}});
app.get('/api/admin/dashboard',auth,permit('orders'),async(req,res)=>{const orders=await Order.find();const paid=orders.filter(x=>x.payment?.state==='PAID');res.json({ordersToday:orders.length,revenuePaise:paid.reduce((a,x)=>a+x.totalPaise,0),pendingKitchen:orders.filter(x=>['CONFIRMED','ACCEPTED','PREPARING'].includes(x.status)).length});});
app.get('/api/admin/orders',auth,permit('orders'),async(req,res,next)=>{try{res.json(await Order.find({'payment.state':'PAID'}).sort({createdAt:-1}).lean())}catch(error){next(error)}});
app.get('/api/admin/revenue',auth,permit('orders'),async(req,res,next)=>{try{const orders=await Order.find({'payment.state':'PAID'}).lean();res.json({paidPaise:orders.reduce((sum,o)=>sum+o.totalPaise,0),deliveryPaise:orders.reduce((sum,o)=>sum+o.deliveryPaise,0),platformPaise:orders.reduce((sum,o)=>sum+o.platformFeePaise,0),count:orders.length})}catch(error){next(error)}});
app.get('/api/admin/riders',auth,permit('riders'),async(req,res,next)=>{try{res.json(await Profile.find({role:'RIDER'}).select('fullName email mobile role createdAt').lean())}catch(error){next(error)}});
app.post('/api/admin/riders',auth,permit('riders'),async(req,res,next)=>{try{const email=String(req.body.email||'').trim().toLowerCase();if(!/^\S+@\S+\.\S+$/.test(email))return res.status(400).json({error:'Enter a valid rider email'});res.status(201).json(await Profile.findOneAndUpdate({email},{$set:{email,role:'RIDER'}},{new:true,upsert:true,setDefaultsOnInsert:true}))}catch(error){next(error)}});
app.get('/api/admin/riders/online',auth,permit('orders'),async(req,res,next)=>{try{res.json(await Profile.find({role:'RIDER',riderOnline:true}).select('supabaseId fullName email mobile').lean())}catch(error){next(error)}});
app.patch('/api/admin/orders/:id/assign-rider',auth,permit('orders'),async(req,res,next)=>{try{const rider=await Profile.findOne({supabaseId:req.body.riderId,role:'RIDER',riderOnline:true});if(!rider)return res.status(400).json({error:'Choose an online rider'});const order=await Order.findByIdAndUpdate(req.params.id,{$set:{riderId:rider.supabaseId,status:'OUT_FOR_DELIVERY'},$push:{statusHistory:{status:'OUT_FOR_DELIVERY',actor:req.user.id,note:`Assigned to ${rider.fullName||rider.email}`,at:new Date()}}},{new:true});if(!order)return res.status(404).json({error:'Order not found'});res.json(order)}catch(error){next(error)}});
app.route('/api/admin/menu').get(auth,permit('menu'),async(req,res)=>res.json(await MenuItem.find())).post(auth,permit('menu'),async(req,res)=>res.status(201).json(await MenuItem.create(req.body))).patch(auth,permit('menu'),async(req,res)=>res.json(await MenuItem.findByIdAndUpdate(req.body.id,req.body,{new:true,runValidators:true}))).delete(auth,permit('menu'),async(req,res)=>{const item=await MenuItem.findByIdAndDelete(req.body.id);if(!item)return res.status(404).json({error:'Menu item not found'});res.status(204).end()});
app.route('/api/admin/settings').get(auth,permit('settings'),async(req,res)=>res.json(await settings())).patch(auth,permit('settings'),async(req,res)=>res.json(await Settings.findOneAndUpdate({},req.body,{new:true,upsert:true})));
app.use((err,req,res,next)=>{console.error(err);res.status(err.status||500).json({error:err.message||'Unexpected server error'});});
mongoose.connect(process.env.MONGODB_URI).then(()=>app.listen(process.env.PORT||4000,()=>console.log(`Godavari API on :${process.env.PORT||4000}`))).catch(err=>{console.error('MongoDB connection failed:',err.message);process.exit(1)});
