require('dotenv').config();const express=require('express'),cors=require('cors'),mongoose=require('mongoose'),crypto=require('crypto'),Razorpay=require('razorpay');const {MenuItem,Settings,Order,Profile}=require('./models');const {auth,permit}=require('./auth');
const app=express();app.use(cors({origin:process.env.CLIENT_URL?.split(',')||true}));app.use(express.json({limit:'1mb'}));
const razorpay=process.env.RAZORPAY_KEY_ID?new Razorpay({key_id:process.env.RAZORPAY_KEY_ID,key_secret:process.env.RAZORPAY_KEY_SECRET}):null;const paise=n=>Math.round(Number(n)||0);
async function settings(){return await Settings.findOne()||await Settings.create({});}
async function calculateQuote(body){const s=await settings(),items=body.items||[];const ids=items.map(x=>x.itemId);const menu=await MenuItem.find({_id:{$in:ids},available:true}).lean();if(!items.length||menu.length!==ids.length){const error=new Error('One or more items are unavailable');error.status=400;throw error}let subtotal=0;for(const line of items){const item=menu.find(x=>String(x._id)===line.itemId);subtotal+=item.pricePaise*paise(line.quantity);for(const selected of line.modifierNames||[]){const m=item.modifiers.find(x=>x.active&&x.name===selected);if(!m){const error=new Error('Invalid modifier');error.status=400;throw error}subtotal+=m.pricePaise*paise(line.quantity)}}const delivery=s.deliveryBasePaise+(Math.max(0,Number(body.distanceKm)||0)*s.deliveryPerKmPaise);const tax=Math.round(subtotal*s.taxBps/10000),gateway=s.gatewayFeeEnabled?Math.round(subtotal*s.gatewayFeeBps/10000):0;return {subtotalPaise:subtotal,taxPaise:tax,deliveryPaise:delivery,platformFeePaise:s.platformFeePaise,gatewayFeePaise:gateway,totalPaise:subtotal+tax+delivery+s.platformFeePaise+gateway}}
app.get('/api/health',(req,res)=>res.json({ok:true,mongo:mongoose.connection.readyState===1}));
app.post('/api/auth/profile',auth,async(req,res)=>{const fullName=String(req.body.fullName||'').trim(),mobile=String(req.body.mobile||'').trim();if(fullName.length<2||!/^\+?[0-9]{10,15}$/.test(mobile))return res.status(400).json({error:'Enter your full name and a valid mobile number'});const admins=(process.env.ADMIN_EMAILS||'').split(',').map(x=>x.trim().toLowerCase());const role=admins.includes(String(req.user.email).toLowerCase())?'OWNER':'CUSTOMER';const profile=await Profile.findOneAndUpdate({supabaseId:req.user.id},{email:req.user.email,fullName,mobile,role,onboardingComplete:true},{new:true,upsert:true,setDefaultsOnInsert:true});res.json(profile)});
app.get('/api/auth/me',auth,async(req,res)=>{const profile=await Profile.findOne({supabaseId:req.user.id});res.json({...req.user,onboardingComplete:profile?.onboardingComplete||false})});
app.get('/api/menu',async(req,res)=>res.json(await MenuItem.find({available:true}).sort({category:1,name:1}).lean()));
app.post('/api/delivery/quote',async(req,res,next)=>{try{res.json(await calculateQuote(req.body))}catch(error){next(error)}});
app.post('/api/payments/razorpay/create',async(req,res)=>{if(!razorpay)return res.status(503).json({error:'Razorpay is not configured'});const amount=paise(req.body.amountPaise);if(amount<100)return res.status(400).json({error:'Invalid amount'});const payment=await razorpay.orders.create({amount,currency:'INR',receipt:`gd_${Date.now()}`});res.json({id:payment.id,amount:payment.amount,currency:payment.currency,keyId:process.env.RAZORPAY_KEY_ID});});
app.post('/api/payments/razorpay/verify',async(req,res)=>{const {razorpay_order_id,razorpay_payment_id,razorpay_signature}=req.body;const expected=crypto.createHmac('sha256',process.env.RAZORPAY_KEY_SECRET).update(`${razorpay_order_id}|${razorpay_payment_id}`).digest('hex');if(!crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(razorpay_signature)))return res.status(400).json({error:'Invalid payment signature'});res.json({verified:true});});
app.post('/api/orders',async(req,res,next)=>{try{const q=await calculateQuote(req.body);const order=await Order.create({...req.body,subtotalPaise:q.subtotalPaise,taxPaise:q.taxPaise,deliveryPaise:q.deliveryPaise,platformFeePaise:q.platformFeePaise,gatewayFeePaise:q.gatewayFeePaise,totalPaise:q.totalPaise,status:'PAYMENT_PENDING'});res.status(201).json(order)}catch(error){next(error)}});
app.get('/api/admin/dashboard',auth,permit('orders'),async(req,res)=>{const orders=await Order.find();const paid=orders.filter(x=>x.payment?.state==='PAID');res.json({ordersToday:orders.length,revenuePaise:paid.reduce((a,x)=>a+x.totalPaise,0),pendingKitchen:orders.filter(x=>['CONFIRMED','ACCEPTED','PREPARING'].includes(x.status)).length});});
app.route('/api/admin/menu').get(auth,permit('menu'),async(req,res)=>res.json(await MenuItem.find())).post(auth,permit('menu'),async(req,res)=>res.status(201).json(await MenuItem.create(req.body))).patch(auth,permit('menu'),async(req,res)=>res.json(await MenuItem.findByIdAndUpdate(req.body.id,req.body,{new:true,runValidators:true})));
app.route('/api/admin/settings').get(auth,permit('settings'),async(req,res)=>res.json(await settings())).patch(auth,permit('settings'),async(req,res)=>res.json(await Settings.findOneAndUpdate({},req.body,{new:true,upsert:true})));
app.use((err,req,res,next)=>{console.error(err);res.status(err.status||500).json({error:err.message||'Unexpected server error'});});
mongoose.connect(process.env.MONGODB_URI).then(()=>app.listen(process.env.PORT||4000,()=>console.log(`Godavari API on :${process.env.PORT||4000}`))).catch(err=>{console.error('MongoDB connection failed:',err.message);process.exit(1)});
