require('dotenv').config();
const express=require('express'),cors=require('cors'),mongoose=require('mongoose'),crypto=require('crypto'),bcrypt=require('bcryptjs'),Razorpay=require('razorpay');
const {MenuItem,Settings,Order,Profile,DailyReport}=require('./models');
const {auth,permit,issue}=require('./auth');
const app=express();
app.use(cors({origin:process.env.CLIENT_URL?.split(',').map(x=>x.trim()).filter(Boolean)||true}));app.use(express.json({limit:'1mb'}));
const razorpay=process.env.RAZORPAY_KEY_ID?new Razorpay({key_id:process.env.RAZORPAY_KEY_ID,key_secret:process.env.RAZORPAY_KEY_SECRET}):null;
const paise=n=>Math.round(Number(n)||0),money=n=>`₹${(n/100).toLocaleString('en-IN',{maximumFractionDigits:2})}`;
const mobile=v=>String(v||'').replace(/\D/g,'');
async function settings(){const result=await Settings.findOne()||await Settings.create({});let changed=false;for(const [key,value] of Object.entries({taxBps:0,deliveryBasePaise:1500,itemPackagingPaise:0})){if(result[key]!==value){result[key]=value;changed=true}}if(changed)await result.save();return result;}
async function calculateQuote(body){const s=await settings(),items=body.items||[];if(!s.ordersEnabled){const e=new Error('We are closed for orders right now.');e.status=503;throw e}const ids=items.map(x=>x.itemId),menu=await MenuItem.find({_id:{$in:ids},available:true}).lean();if(!items.length||menu.length!==ids.length){const e=new Error('One or more items are unavailable.');e.status=400;throw e}let subtotal=0;for(const line of items){const item=menu.find(x=>String(x._id)===String(line.itemId)),qty=paise(line.quantity);if(!item||qty<1){const e=new Error('Cart quantities are invalid.');e.status=400;throw e}subtotal+=item.pricePaise*qty;for(const selected of line.modifierNames||[]){const m=item.modifiers.find(x=>x.active&&x.name===selected);if(!m){const e=new Error('Invalid modifier.');e.status=400;throw e}subtotal+=m.pricePaise*qty}}const gateway=s.gatewayFeeEnabled?Math.round(subtotal*(s.gatewayFeeBps||100)/10000):0,platform=s.platformFeeEnabled?s.platformFeePaise:0;return {subtotalPaise:subtotal,taxPaise:0,deliveryPaise:1500,packagingPaise:0,platformFeePaise:platform,gatewayFeePaise:gateway,totalPaise:subtotal+1500+platform+gateway};}
function publicProfile(profile){return {id:String(profile._id),fullName:profile.fullName,mobile:profile.mobile,role:profile.role,onboardingComplete:profile.onboardingComplete};}
async function createInitialAdmin(){const name=String(process.env.INITIAL_ADMIN_NAME||'').trim(),number=mobile(process.env.INITIAL_ADMIN_MOBILE),password=String(process.env.INITIAL_ADMIN_PASSWORD||'');if(!name||!number||!password)return;const passwordHash=await bcrypt.hash(password,12);await Profile.findOneAndUpdate({mobile:number},{$set:{fullName:name,mobile:number,passwordHash,role:'OWNER',onboardingComplete:true}},{upsert:true,new:true,setDefaultsOnInsert:true});console.log('Initial admin account is ready.');}
function todayIST(date=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata'}).format(date);}
function boundsForIST(dateKey){const [y,m,d]=dateKey.split('-').map(Number),start=new Date(Date.UTC(y,m-1,d-1,18,30)),end=new Date(start.getTime()+86400000);return {start,end};}
function reportHtml(date,orders,total){const lines=orders.map(o=>`<li><b>#${String(o._id).slice(-6).toUpperCase()}</b> — ${o.customer.name} (${o.customer.mobile}) — ${o.items.map(i=>`${i.name} × ${i.quantity}`).join(', ')} — <b>${money(o.totalPaise)}</b></li>`).join('');return `<h1>Godavari daily order report</h1><p><b>Date:</b> ${date}</p><p><b>Paid orders:</b> ${orders.length}<br><b>Amount received:</b> ${money(total)}</p><h2>Orders</h2><ol>${lines||'<li>No paid orders.</li>'}</ol>`;}
async function sendDailyReport(dateKey){if(await DailyReport.findOne({reportDate:dateKey}))return {skipped:true};if(!process.env.RESEND_API_KEY||!process.env.REPORT_TO_EMAIL)throw new Error('RESEND_API_KEY and REPORT_TO_EMAIL must be configured before reports can be sent.');const {start,end}=boundsForIST(dateKey),orders=await Order.find({'payment.state':'PAID',createdAt:{$gte:start,$lt:end}}).lean(),total=orders.reduce((sum,o)=>sum+o.totalPaise,0);const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:process.env.REPORT_FROM_EMAIL||'Godavari <onboarding@resend.dev>',to:[process.env.REPORT_TO_EMAIL],subject:`Godavari orders — ${dateKey}`,html:reportHtml(dateKey,orders,total)})});const email=await response.json();if(!response.ok)throw new Error(email.message||'Could not send daily email report.');await DailyReport.create({reportDate:dateKey,emailId:email.id,orderCount:orders.length,totalPaise:total});if(orders.length)await Order.deleteMany({_id:{$in:orders.map(x=>x._id)}});return {sent:true,orderCount:orders.length,totalPaise:total};}
let latestMinute='';function scheduleDailyReport(){setInterval(async()=>{const now=new Date(),parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(now),hour=parts.find(x=>x.type==='hour')?.value,minute=parts.find(x=>x.type==='minute')?.value,key=`${todayIST(now)}-${hour}:${minute}`;if(hour!=='23'||minute!=='59'||key===latestMinute)return;latestMinute=key;try{await sendDailyReport(todayIST(now));console.log('Daily report sent.')}catch(error){console.error('Daily report failed:',error.message)}},30000);}
app.get('/api/health',(req,res)=>res.json({ok:true,mongo:mongoose.connection.readyState===1}));
app.post('/api/auth/register',async(req,res,next)=>{try{const fullName=String(req.body.fullName||'').trim(),number=mobile(req.body.mobile),password=String(req.body.password||'');if(fullName.length<2||number.length!==10||password.length<8)return res.status(400).json({error:'Enter your name, a 10-digit mobile number, and a password of at least 8 characters.'});if(await Profile.findOne({mobile:number}))return res.status(409).json({error:'An account already exists for this mobile number. Please sign in.'});const profile=await Profile.create({authId:crypto.randomUUID(),fullName,mobile:number,passwordHash:await bcrypt.hash(password,12),onboardingComplete:true});res.status(201).json({token:issue(profile),user:publicProfile(profile)});}catch(error){next(error)}});
app.post('/api/auth/login',async(req,res,next)=>{try{const profile=await Profile.findOne({mobile:mobile(req.body.mobile)});if(!profile||!await bcrypt.compare(String(req.body.password||''),profile.passwordHash))return res.status(401).json({error:'Incorrect mobile number or password.'});res.json({token:issue(profile),user:publicProfile(profile)});}catch(error){next(error)}});
app.get('/api/auth/me',auth,async(req,res)=>{const profile=await Profile.findById(req.user.id);res.json(publicProfile(profile));});
app.post('/api/auth/profile',auth,async(req,res,next)=>{try{const fullName=String(req.body.fullName||'').trim(),number=mobile(req.body.mobile);if(fullName.length<2||number.length!==10)return res.status(400).json({error:'Enter your full name and a valid 10-digit mobile number.'});const duplicate=await Profile.findOne({mobile:number,_id:{$ne:req.user.id}});if(duplicate)return res.status(409).json({error:'That mobile number is already used by another account.'});const profile=await Profile.findByIdAndUpdate(req.user.id,{$set:{fullName,mobile:number,onboardingComplete:true}},{new:true});res.json(publicProfile(profile));}catch(error){next(error)}});
app.get('/api/menu',async(req,res,next)=>{try{const items=await MenuItem.find({}).sort({category:1,name:1}).lean();res.json(items.map(item=>({...item,description:`${item.category}${item.description?` · ${item.description}`:''}`})));}catch(error){next(error)}});
app.post('/api/delivery/quote',async(req,res,next)=>{try{res.json(await calculateQuote(req.body));}catch(error){next(error)}});
app.post('/api/orders',auth,async(req,res,next)=>{try{const address=String(req.body.customer?.address||'').trim();if(!address)return res.status(400).json({error:'Add a delivery address before ordering.'});const quote=await calculateQuote(req.body),menu=await MenuItem.find({_id:{$in:req.body.items.map(x=>x.itemId)}}).lean(),items=req.body.items.map(line=>{const item=menu.find(x=>String(x._id)===String(line.itemId));return {itemId:item._id,name:item.name,quantity:paise(line.quantity),unitPricePaise:item.pricePaise,modifiers:[]};});const order=await Order.create({customerId:req.user.id,customer:{name:req.user.fullName,mobile:req.user.mobile,address,landmark:String(req.body.customer?.landmark||'')},items,...quote,status:'PAYMENT_PENDING',statusHistory:[{status:'PAYMENT_PENDING',actor:req.user.id,note:'Order created',at:new Date()}]});res.status(201).json(order);}catch(error){next(error)}});
app.post('/api/payments/razorpay/create',auth,async(req,res,next)=>{try{if(!razorpay)return res.status(503).json({error:'Razorpay is not configured.'});const order=await Order.findOne({_id:req.body.orderId,customerId:req.user.id,status:'PAYMENT_PENDING'});if(!order)return res.status(404).json({error:'Pending order not found.'});if(order.payment?.razorpayOrderId)return res.json({id:order.payment.razorpayOrderId,amount:order.totalPaise,currency:'INR',keyId:process.env.RAZORPAY_KEY_ID});const payment=await razorpay.orders.create({amount:order.totalPaise,currency:'INR',receipt:`gd_${order._id}`});order.payment={provider:'razorpay',state:'PENDING',razorpayOrderId:payment.id};await order.save();res.json({id:payment.id,amount:payment.amount,currency:payment.currency,keyId:process.env.RAZORPAY_KEY_ID});}catch(error){next(error)}});
app.post('/api/payments/razorpay/verify',auth,async(req,res,next)=>{try{const {razorpay_order_id,razorpay_payment_id,razorpay_signature,orderId}=req.body,order=await Order.findOne({_id:orderId,customerId:req.user.id});if(!order)return res.status(404).json({error:'Order not found.'});const expected=crypto.createHmac('sha256',process.env.RAZORPAY_KEY_SECRET).update(`${razorpay_order_id}|${razorpay_payment_id}`).digest('hex'),received=String(razorpay_signature||'');if(!received||!crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(received)))return res.status(400).json({error:'Invalid payment signature.'});if(order.payment?.state==='PAID')return res.json({verified:true});order.payment={provider:'razorpay',state:'PAID',razorpayOrderId:razorpay_order_id,razorpayPaymentId:razorpay_payment_id};order.status='CONFIRMED';order.statusHistory.push({status:'CONFIRMED',actor:'payment',note:'Payment verified',at:new Date()});await order.save();res.json({verified:true,orderId:order.id});}catch(error){next(error)}});
app.get('/api/orders/mine',auth,async(req,res,next)=>{try{res.json(await Order.find({customerId:req.user.id,'payment.state':'PAID'}).sort({createdAt:-1}).lean());}catch(error){next(error)}});
app.get('/api/admin/dashboard',auth,permit('orders'),async(req,res,next)=>{try{const orders=await Order.find({'payment.state':'PAID'}).lean();res.json({ordersToday:orders.length,revenuePaise:orders.reduce((a,x)=>a+x.totalPaise,0),pendingKitchen:orders.filter(x=>x.status==='CONFIRMED').length});}catch(error){next(error)}});
app.get('/api/admin/orders',auth,permit('orders'),async(req,res,next)=>{try{res.json(await Order.find({'payment.state':'PAID'}).sort({createdAt:-1}).lean());}catch(error){next(error)}});
app.get('/api/admin/revenue',auth,permit('orders'),async(req,res,next)=>{try{const orders=await Order.find({'payment.state':'PAID'}).lean();res.json({paidPaise:orders.reduce((sum,o)=>sum+o.totalPaise,0),deliveryPaise:orders.reduce((sum,o)=>sum+o.deliveryPaise,0),platformPaise:orders.reduce((sum,o)=>sum+o.platformFeePaise,0),count:orders.length});}catch(error){next(error)}});
app.get('/api/admin/admins',auth,permit('admins'),async(req,res,next)=>{try{res.json(await Profile.find({role:{$in:['OWNER','OPERATIONS']}}).select('fullName mobile role createdAt').lean());}catch(error){next(error)}});
app.post('/api/admin/admins',auth,permit('admins'),async(req,res,next)=>{try{const fullName=String(req.body.fullName||'').trim(),number=mobile(req.body.mobile),password=String(req.body.password||''),role=req.body.role==='OWNER'?'OWNER':'OPERATIONS';if(fullName.length<2||number.length!==10||password.length<8)return res.status(400).json({error:'Name, 10-digit mobile number, and an 8-character password are required.'});if(await Profile.findOne({mobile:number}))return res.status(409).json({error:'An account already exists for this mobile number.'});const profile=await Profile.create({authId:crypto.randomUUID(),fullName,mobile:number,passwordHash:await bcrypt.hash(password,12),role,onboardingComplete:true});res.status(201).json(publicProfile(profile));}catch(error){next(error)}});
app.route('/api/admin/menu').get(auth,permit('menu'),async(req,res)=>res.json(await MenuItem.find())).post(auth,permit('menu'),async(req,res)=>res.status(201).json(await MenuItem.create(req.body))).patch(auth,permit('menu'),async(req,res)=>res.json(await MenuItem.findByIdAndUpdate(req.body.id,req.body,{new:true,runValidators:true}))).delete(auth,permit('menu'),async(req,res)=>{const item=await MenuItem.findByIdAndDelete(req.body.id);if(!item)return res.status(404).json({error:'Menu item not found.'});res.status(204).end();});
app.route('/api/admin/settings').get(auth,permit('settings'),async(req,res)=>res.json(await settings())).patch(auth,permit('settings'),async(req,res)=>res.json(await Settings.findOneAndUpdate({},req.body,{new:true,upsert:true})));
app.post('/api/admin/reports/daily',async(req,res,next)=>{try{if(req.headers.authorization!==`Bearer ${process.env.REPORT_SECRET}`)return res.status(401).json({error:'Unauthorized'});res.json(await sendDailyReport(req.body?.date||todayIST()));}catch(error){next(error)}});
app.use((error,req,res,next)=>{console.error(error);res.status(error.status||500).json({error:error.message||'Unexpected server error.'});});
mongoose.connect(process.env.MONGODB_URI).then(async()=>{await createInitialAdmin();scheduleDailyReport();app.listen(process.env.PORT||4000,()=>console.log(`Godavari API on :${process.env.PORT||4000}`));}).catch(error=>{console.error('MongoDB connection failed:',error.message);process.exit(1);});
